### ISSUE TITLE
[Add] psychological safety measure

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#11]
Probably from: Edmondson, Amy. 1999. “Psychological Safety and Learning Behavior in Work Teams.” Administrative Science Quarterly 44 (2): 350–83.

**Comment by JamesPHoughton** [comment]
Adapted in _Nicole Abi-Esber, Alison Wood Brooks, and Ethan Burris. “Feeling Seen: Leader Eye Gaze Promotes Psychological Safety, Participation, and Voice.”_ as:

> 1. During this conversation I felt if I made a mistake, the other people in the group would 
> hold it against me. (R)
> 2. During this conversation I felt the other people in the group were able to bring up 
> problems and tough issues. 
> 3. During this conversation I felt the other people in the group sometimes rejected others for being different. (R)
> 4. During this conversation I felt it was safe to take a risk with the other people in the group. 
> 5. During this conversation I felt like it was difficult to ask the other players for help. (R)
> 6. During this conversation I felt like no one would deliberately act in a way that 
> undermined me and my efforts.
> 7. During this conversation I felt like my unique skills and talents were valued and utilized  while working with the other people in the group.

**Comment by sky1113** [comment]
I'm not sure if you wanted this survey checked as well, but it looks to be very similar to the questions in the original survey and has not been "adapted" much.

**Comment by sky1113** [comment]
Also, it looks like these new surveys mostly use 7-point scales as opposed to the 5-point ones we were previously using. I wanted to confirm that I should implement a 7-point scale and ask if changing our 5-point scales to 7-point scales would be something you would be interested in seeing.

**Comment by sky1113** [comment]
- [ ]  Create a new folder in surveys/src/surveys w/ descriptive, easy-to-read name superSpecialSurvey/
- [ ]  Create SurveyJS .json file (e.g. superSpecialSurvey/superSpecialSurvey.json)
- [ ]  Create a .bib file citing your references for the survey (always: references.bib)
- [ ]  Create a storybook markdown file to document (e.g. superSpecialSurvey.stories.mdx)
  - [ ]  Survey purpose
  - [ ]  Expected behavior
  - [ ]  Design rationale
  - [ ]  APA-style bibliography
- [ ]  Create file with function to aggregate survey data (e.g. superSpecialSurvey.score.js)
- [ ]  Create PR and link to this issue

**Comment by JamesPHoughton** [comment]
From the original paper:
![image](https://user-images.githubusercontent.com/4304478/201154365-0565227d-e043-433f-bb67-c14cc38e9303.png)
