### ISSUE TITLE
Political identification survey

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#34]
We want to measure participants' party identifications. This is a survey that we will probably use many times in lots of different experiments, and so needs to be bulletproof. We should see what is done in ANES, PEW, GSS, and possibly other surveys (Census?) and arrive at the least controversial way of asking this set of questions. 

I expect we will ask something about both party id (republican/democrat) and ideology (liberal/conservative). This may or may not be a unidimensional scale, i.e. we could have a different scale for "how much do you identify with the republican party"? "With the democratic party"? "As a libertarian"? etc. 

Let's use this issue to identify alternative presentations of the question and identify which one we are going to use and why.

@markwhiting, @linneagandhi, @TutiGomoka, do you know if we already have something like this in the turkers panel?

**Comment by isaacgat** [comment]
Hi Tuti, I have a few questions about the survey.

1. I notice our survey question about partisan split is coded between Democrat, Republican, Independent, and Other, but I am curious if this is a collapsed variable (were you measuring along a greater scale, e.g., 1-7?) that could tell us more about the independent leaners. If not, we should rethink how we gather this information because the label "independent" is not as informative as we might like. A lot of Americans are independents but only a small portion of those are pure independents. We need to measure partisan lean because it is just as predictive as pure partisan split (see [Myth 2](https://themonkeycage.org/2009/12/three_myths_about_political_in/)). 
3. It looks like the first paper asks participants to identify ideology on a 5-point Likert scale, whereas the second paper asks participants to identify partisanship on a 7-point scale (see [codebook](https://osf.io/yxu2a/)). We should probably standardize this and make these scales similar.

**Comment by markwhiting** [comment]
@isaacgat it depends a bit on which model of political identity you adhere to, and our approach is in part intended to cover several bases in that regard. The party identification question is more around how you register, or would register, however, there's absolutely room to ask something more nuanced, but I'd probably do that in addition to what we have now, as opposed to instead. i.e., a secondary question that asks for leaning specifically.

We use the 5 point version for both fiscal and social in our demographics instrument, but we also normalize these for standardization across other data sources that we have inducted into our panel in a relatively standard approach. 

We're always interested to improve our panel instruments as they are used by several groups in the lab. So if you find a lean question that we could add in here, that might be very useful.

**Comment by isaacgat** [comment]
@markwhiting Thank you for clarifying! I see how having data about political affiliation w.r.t. voting is valuable. I had a conservation with James and Tuti before lunch about the question structure and we seemed to agree that the current question is part of a larger question branch (per the screengrab that Tuti sent) that we may consider gathering from future participants for our study. In our case, we are highly interested in the lean of our respondents because we want to test the measurable impact of the deliberation on people across the broad spectrum of political backgrounds. So the lean questions that we might add are follow-ups that are included by Rand in his question documentation. I am currently researching the breakdown of these spectrum Likert scale questions into more digestible questions and then summarizing the variables ex post facto (like Rand and the ANES seem to do). If there appears to be an agreed-upon way of structuring these questions, I will note those findings here.

**Comment by TutiGomoka** [comment]
@markwhiting; One thing that Isaac mentioned in our conversation that I found interesting is that the results/scale recorded for the partisanship question in that Rand paper was sort of derived from that first political registration question + the follow up leaning questions to = a 7-point Likert scale in the results. Whereas right now in the panel we just have our political party responses recorded as democrat, republican, neutral etc. 
Is that something we want to think about?

**Comment by markwhiting** [comment]
One of the major criticisms of doing this is that it assumes that independents are between two extremes (republicans and democrats). I think the standard argument for moving beyond this is to ask political leaning questions, e.g., the fiscal and social questions we have, so that people's identity can be mapped in a higher dimensional space. 

Again, I think there remains a fair amount of disagreement in the literature about the best possible way to do this, but I think the questions we ask let us explore that space reasonably well. 

I'd probably lean away from trying to treat political lean as a single dimension, and instead use some of the more nuanced approaches some people take. Josh Ludan, someone who works (or used to work) with Homa may have done a bit more digging here and have a more nuanced awareness of the latest suggestions.

**Comment by isaacgat** [comment]
Hi @markwhiting and @TutiGomoka,

James and I have agreed that we should gather the full scope of the partisan divide in the two-question Likert question per the Rand survey. Although the literature is split on whether or not the two-question Likert scale is superior, it appears that Rand's full metric is preferable because it gives us a larger pool of partisans to pick from as we can include leaners in our analysis. Furthermore, [Levendusky (2018)](https://www.journals.uchicago.edu/doi/suppl/10.1086/693987/suppl_file/160415Appendix.pdf) uses a single-question 7-point Likert scale to measure ideology breakdown while using the tiered responses to measure the Republican-Democrat in the same survey. My gut feeling is that this is appropriate given that we think of the left-right as a spectrum while the Republican-Democrat split is less linear. In any event, this reassures us that we are good to use a single Likert question to measure ideology while using a two-part Likert question to measure partisan divide as we have set up (mixing and matching types has been done successfully before).

@JamesPHoughton has thoughts on how to collect this additional party ID data that he will comment on here.

**Comment by markwhiting** [comment]
Sounds great.

**Comment by JamesPHoughton** [comment]
Next step for this is to add a question to the basic panel survey? @TutiGomoka how would we do that?

**Comment by JamesPHoughton** [comment]
For the US, added this standard survey: https://github.com/Watts-Lab/surveys/tree/main/surveys/politicalPartyUS
